os:
    - linux
    - osx
language: generic
osx_image: xcode10.2
sudo: required
dist: trusty
env:
    - SWIFT_VERSION=5.0
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
    - swift test
